version: "3"

services:
  flow-percona:
    image: "percona:ps-8.0.16-7"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: fulltext
      MYSQL_USER:  fulltext_user
      MYSQL_PASSWORD: Pass123456#