spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fulltext
    username: fulltext_user
    password: Pass123456#
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
